apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone-app
  labels:
    app: netflix-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
      - name: netflix-clone-app
        image: ghcr.io/your-github-username/netflix-clone-react-typescript:latest # Placeholder
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-key
              key: TMDB_V3_API_KEY
        - name: VITE_APP_API_ENDPOINT_URL
          value: "https://api.themoviedb.org/3"
