apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Add resources specific to the staging environment
- ingress.yaml

# Set the namespace for all resources in this overlay
namespace: staging
